// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.8
// source: objDetectMod.proto

// option go_package = "goagent/service";

package objdetectgrpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InitArg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LabelPath  string `protobuf:"bytes,1,opt,name=label_path,json=labelPath,proto3" json:"label_path,omitempty"`
	NumClasses int32  `protobuf:"varint,2,opt,name=num_classes,json=numClasses,proto3" json:"num_classes,omitempty"`
	QueueSize  int32  `protobuf:"varint,3,opt,name=queue_size,json=queueSize,proto3" json:"queue_size,omitempty"` // string gpudev = 4;
}

func (x *InitArg) Reset() {
	*x = InitArg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_objDetectMod_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InitArg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitArg) ProtoMessage() {}

func (x *InitArg) ProtoReflect() protoreflect.Message {
	mi := &file_objDetectMod_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitArg.ProtoReflect.Descriptor instead.
func (*InitArg) Descriptor() ([]byte, []int) {
	return file_objDetectMod_proto_rawDescGZIP(), []int{0}
}

func (x *InitArg) GetLabelPath() string {
	if x != nil {
		return x.LabelPath
	}
	return ""
}

func (x *InitArg) GetNumClasses() int32 {
	if x != nil {
		return x.NumClasses
	}
	return 0
}

func (x *InitArg) GetQueueSize() int32 {
	if x != nil {
		return x.QueueSize
	}
	return 0
}

type InferenceArg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ModelPath              string `protobuf:"bytes,1,opt,name=model_path,json=modelPath,proto3" json:"model_path,omitempty"`
	VideoPath              string `protobuf:"bytes,2,opt,name=video_path,json=videoPath,proto3" json:"video_path,omitempty"`
	OverlapOutputDir       string `protobuf:"bytes,3,opt,name=overlap_output_dir,json=overlapOutputDir,proto3" json:"overlap_output_dir,omitempty"`
	OverlapOutput          string `protobuf:"bytes,4,opt,name=overlap_output,json=overlapOutput,proto3" json:"overlap_output,omitempty"`
	DetectedOutput         string `protobuf:"bytes,5,opt,name=detected_output,json=detectedOutput,proto3" json:"detected_output,omitempty"`
	DetectedOutputDir      string `protobuf:"bytes,6,opt,name=detected_output_dir,json=detectedOutputDir,proto3" json:"detected_output_dir,omitempty"`
	OutputLabeledVideoPath string `protobuf:"bytes,7,opt,name=output_labeled_video_path,json=outputLabeledVideoPath,proto3" json:"output_labeled_video_path,omitempty"`
}

func (x *InferenceArg) Reset() {
	*x = InferenceArg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_objDetectMod_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InferenceArg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InferenceArg) ProtoMessage() {}

func (x *InferenceArg) ProtoReflect() protoreflect.Message {
	mi := &file_objDetectMod_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InferenceArg.ProtoReflect.Descriptor instead.
func (*InferenceArg) Descriptor() ([]byte, []int) {
	return file_objDetectMod_proto_rawDescGZIP(), []int{1}
}

func (x *InferenceArg) GetModelPath() string {
	if x != nil {
		return x.ModelPath
	}
	return ""
}

func (x *InferenceArg) GetVideoPath() string {
	if x != nil {
		return x.VideoPath
	}
	return ""
}

func (x *InferenceArg) GetOverlapOutputDir() string {
	if x != nil {
		return x.OverlapOutputDir
	}
	return ""
}

func (x *InferenceArg) GetOverlapOutput() string {
	if x != nil {
		return x.OverlapOutput
	}
	return ""
}

func (x *InferenceArg) GetDetectedOutput() string {
	if x != nil {
		return x.DetectedOutput
	}
	return ""
}

func (x *InferenceArg) GetDetectedOutputDir() string {
	if x != nil {
		return x.DetectedOutputDir
	}
	return ""
}

func (x *InferenceArg) GetOutputLabeledVideoPath() string {
	if x != nil {
		return x.OutputLabeledVideoPath
	}
	return ""
}

type Scores struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Score []float32 `protobuf:"fixed32,1,rep,packed,name=score,proto3" json:"score,omitempty"`
}

func (x *Scores) Reset() {
	*x = Scores{}
	if protoimpl.UnsafeEnabled {
		mi := &file_objDetectMod_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Scores) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Scores) ProtoMessage() {}

func (x *Scores) ProtoReflect() protoreflect.Message {
	mi := &file_objDetectMod_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Scores.ProtoReflect.Descriptor instead.
func (*Scores) Descriptor() ([]byte, []int) {
	return file_objDetectMod_proto_rawDescGZIP(), []int{2}
}

func (x *Scores) GetScore() []float32 {
	if x != nil {
		return x.Score
	}
	return nil
}

type InitOutput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *InitOutput) Reset() {
	*x = InitOutput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_objDetectMod_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InitOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitOutput) ProtoMessage() {}

func (x *InitOutput) ProtoReflect() protoreflect.Message {
	mi := &file_objDetectMod_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitOutput.ProtoReflect.Descriptor instead.
func (*InitOutput) Descriptor() ([]byte, []int) {
	return file_objDetectMod_proto_rawDescGZIP(), []int{3}
}

func (x *InitOutput) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type InferenceOutput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status string  `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Score  float32 `protobuf:"fixed32,2,opt,name=score,proto3" json:"score,omitempty"`
}

func (x *InferenceOutput) Reset() {
	*x = InferenceOutput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_objDetectMod_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InferenceOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InferenceOutput) ProtoMessage() {}

func (x *InferenceOutput) ProtoReflect() protoreflect.Message {
	mi := &file_objDetectMod_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InferenceOutput.ProtoReflect.Descriptor instead.
func (*InferenceOutput) Descriptor() ([]byte, []int) {
	return file_objDetectMod_proto_rawDescGZIP(), []int{4}
}

func (x *InferenceOutput) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *InferenceOutput) GetScore() float32 {
	if x != nil {
		return x.Score
	}
	return 0
}

var File_objDetectMod_proto protoreflect.FileDescriptor

var file_objDetectMod_proto_rawDesc = []byte{
	0x0a, 0x12, 0x6f, 0x62, 0x6a, 0x44, 0x65, 0x74, 0x65, 0x63, 0x74, 0x4d, 0x6f, 0x64, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x6f, 0x62, 0x6a, 0x64, 0x65, 0x74, 0x65, 0x63, 0x74, 0x67,
	0x72, 0x70, 0x63, 0x22, 0x68, 0x0a, 0x07, 0x69, 0x6e, 0x69, 0x74, 0x41, 0x72, 0x67, 0x12, 0x1d,
	0x0a, 0x0a, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x50, 0x61, 0x74, 0x68, 0x12, 0x1f, 0x0a,
	0x0b, 0x6e, 0x75, 0x6d, 0x5f, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x65, 0x73, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x0a, 0x6e, 0x75, 0x6d, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x65, 0x73, 0x12, 0x1d,
	0x0a, 0x0a, 0x71, 0x75, 0x65, 0x75, 0x65, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x09, 0x71, 0x75, 0x65, 0x75, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x22, 0xb5, 0x02,
	0x0a, 0x0c, 0x69, 0x6e, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x41, 0x72, 0x67, 0x12, 0x1d,
	0x0a, 0x0a, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x50, 0x61, 0x74, 0x68, 0x12, 0x1d, 0x0a,
	0x0a, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x50, 0x61, 0x74, 0x68, 0x12, 0x2c, 0x0a, 0x12,
	0x6f, 0x76, 0x65, 0x72, 0x6c, 0x61, 0x70, 0x5f, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x5f, 0x64,
	0x69, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x6f, 0x76, 0x65, 0x72, 0x6c, 0x61,
	0x70, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x44, 0x69, 0x72, 0x12, 0x25, 0x0a, 0x0e, 0x6f, 0x76,
	0x65, 0x72, 0x6c, 0x61, 0x70, 0x5f, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0d, 0x6f, 0x76, 0x65, 0x72, 0x6c, 0x61, 0x70, 0x4f, 0x75, 0x74, 0x70, 0x75,
	0x74, 0x12, 0x27, 0x0a, 0x0f, 0x64, 0x65, 0x74, 0x65, 0x63, 0x74, 0x65, 0x64, 0x5f, 0x6f, 0x75,
	0x74, 0x70, 0x75, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x64, 0x65, 0x74, 0x65,
	0x63, 0x74, 0x65, 0x64, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x12, 0x2e, 0x0a, 0x13, 0x64, 0x65,
	0x74, 0x65, 0x63, 0x74, 0x65, 0x64, 0x5f, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x5f, 0x64, 0x69,
	0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x11, 0x64, 0x65, 0x74, 0x65, 0x63, 0x74, 0x65,
	0x64, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x44, 0x69, 0x72, 0x12, 0x39, 0x0a, 0x19, 0x6f, 0x75,
	0x74, 0x70, 0x75, 0x74, 0x5f, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x65, 0x64, 0x5f, 0x76, 0x69, 0x64,
	0x65, 0x6f, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x16, 0x6f,
	0x75, 0x74, 0x70, 0x75, 0x74, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x65, 0x64, 0x56, 0x69, 0x64, 0x65,
	0x6f, 0x50, 0x61, 0x74, 0x68, 0x22, 0x1e, 0x0a, 0x06, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x73, 0x12,
	0x14, 0x0a, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x18, 0x01, 0x20, 0x03, 0x28, 0x02, 0x52, 0x05,
	0x73, 0x63, 0x6f, 0x72, 0x65, 0x22, 0x24, 0x0a, 0x0a, 0x69, 0x6e, 0x69, 0x74, 0x4f, 0x75, 0x74,
	0x70, 0x75, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x3f, 0x0a, 0x0f, 0x69,
	0x6e, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x12, 0x16,
	0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x32, 0x9a, 0x01, 0x0a,
	0x13, 0x6f, 0x62, 0x6a, 0x44, 0x65, 0x74, 0x65, 0x63, 0x74, 0x4d, 0x6f, 0x64, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x39, 0x0a, 0x04, 0x69, 0x6e, 0x69, 0x74, 0x12, 0x16, 0x2e, 0x6f,
	0x62, 0x6a, 0x64, 0x65, 0x74, 0x65, 0x63, 0x74, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x69, 0x6e, 0x69,
	0x74, 0x41, 0x72, 0x67, 0x1a, 0x19, 0x2e, 0x6f, 0x62, 0x6a, 0x64, 0x65, 0x74, 0x65, 0x63, 0x74,
	0x67, 0x72, 0x70, 0x63, 0x2e, 0x69, 0x6e, 0x69, 0x74, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x12,
	0x48, 0x0a, 0x09, 0x69, 0x6e, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x12, 0x1b, 0x2e, 0x6f,
	0x62, 0x6a, 0x64, 0x65, 0x74, 0x65, 0x63, 0x74, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x69, 0x6e, 0x66,
	0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x41, 0x72, 0x67, 0x1a, 0x1e, 0x2e, 0x6f, 0x62, 0x6a, 0x64,
	0x65, 0x74, 0x65, 0x63, 0x74, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x69, 0x6e, 0x66, 0x65, 0x72, 0x65,
	0x6e, 0x63, 0x65, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x42, 0x10, 0x5a, 0x0e, 0x2f, 0x6f, 0x62,
	0x6a, 0x64, 0x65, 0x74, 0x65, 0x63, 0x74, 0x67, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_objDetectMod_proto_rawDescOnce sync.Once
	file_objDetectMod_proto_rawDescData = file_objDetectMod_proto_rawDesc
)

func file_objDetectMod_proto_rawDescGZIP() []byte {
	file_objDetectMod_proto_rawDescOnce.Do(func() {
		file_objDetectMod_proto_rawDescData = protoimpl.X.CompressGZIP(file_objDetectMod_proto_rawDescData)
	})
	return file_objDetectMod_proto_rawDescData
}

var file_objDetectMod_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_objDetectMod_proto_goTypes = []interface{}{
	(*InitArg)(nil),         // 0: objdetectgrpc.initArg
	(*InferenceArg)(nil),    // 1: objdetectgrpc.inferenceArg
	(*Scores)(nil),          // 2: objdetectgrpc.scores
	(*InitOutput)(nil),      // 3: objdetectgrpc.initOutput
	(*InferenceOutput)(nil), // 4: objdetectgrpc.inferenceOutput
}
var file_objDetectMod_proto_depIdxs = []int32{
	0, // 0: objdetectgrpc.objDetectModservice.init:input_type -> objdetectgrpc.initArg
	1, // 1: objdetectgrpc.objDetectModservice.inference:input_type -> objdetectgrpc.inferenceArg
	3, // 2: objdetectgrpc.objDetectModservice.init:output_type -> objdetectgrpc.initOutput
	4, // 3: objdetectgrpc.objDetectModservice.inference:output_type -> objdetectgrpc.inferenceOutput
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_objDetectMod_proto_init() }
func file_objDetectMod_proto_init() {
	if File_objDetectMod_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_objDetectMod_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InitArg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_objDetectMod_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InferenceArg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_objDetectMod_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Scores); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_objDetectMod_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InitOutput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_objDetectMod_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InferenceOutput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_objDetectMod_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_objDetectMod_proto_goTypes,
		DependencyIndexes: file_objDetectMod_proto_depIdxs,
		MessageInfos:      file_objDetectMod_proto_msgTypes,
	}.Build()
	File_objDetectMod_proto = out.File
	file_objDetectMod_proto_rawDesc = nil
	file_objDetectMod_proto_goTypes = nil
	file_objDetectMod_proto_depIdxs = nil
}
