FROM nvidia/cuda:10.0-cudnn7-runtime
MAINTAINER opnfv

# Deal with error: public key is not available
RUN apt-key adv --keyserver keyserver.ubuntu.com --recv-keys A4B469963BF863CC

RUN apt-get update && apt-get install -y \
        curl \
        wget \
        tmux \
        vim \
        python3 \
        python3-pip \
        libjpeg-dev \
        zlib1g-dev  \
        libfreetype6-dev \
        libsm6 \
        libxext6 \
        libxrender-dev \
        && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*
# remember to remove tmux
# ---

COPY visualNavigationMod/ /root/visualNavigationMod
WORKDIR "/root/visualNavigationMod"

RUN pip3 install "protobuf<4.21.0"
RUN pip3 install --no-cache-dir -r requirement-gpu.txt

EXPOSE 50051
RUN chmod u+x docker-startup.sh

CMD ["./docker-startup.sh"]
