FROM golang:1.16-bullseye
MAINTAINER opnfv

# Deal with error: public key is not available
RUN apt-key adv --keyserver keyserver.ubuntu.com --recv-keys A4B469963BF863CC
RUN apt-get update && apt-get install -y \
        python3 \
        python3-pip \
        && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

COPY simulator/ /root/simulator
WORKDIR "/root/simulator"

RUN pip3 install gdown

RUN gdown 1QOnRO8YyeX-yUcMRMHM2Z4zSI5R13dfF

RUN make controller

CMD ["./controller"]
