# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: objDetectMod.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='objDetectMod.proto',
  package='objdetectgrpc',
  syntax='proto3',
  serialized_options=b'Z\016/objdetectgrpc',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x12objDetectMod.proto\x12\robjdetectgrpc\"F\n\x07initArg\x12\x12\n\nlabel_path\x18\x01 \x01(\t\x12\x13\n\x0bnum_classes\x18\x02 \x01(\x05\x12\x12\n\nqueue_size\x18\x03 \x01(\x05\"\xc3\x01\n\x0cinferenceArg\x12\x12\n\nmodel_path\x18\x01 \x01(\t\x12\x12\n\nvideo_path\x18\x02 \x01(\t\x12\x1a\n\x12overlap_output_dir\x18\x03 \x01(\t\x12\x16\n\x0eoverlap_output\x18\x04 \x01(\t\x12\x17\n\x0f\x64\x65tected_output\x18\x05 \x01(\t\x12\x1b\n\x13\x64\x65tected_output_dir\x18\x06 \x01(\t\x12!\n\x19output_labeled_video_path\x18\x07 \x01(\t\"\x17\n\x06scores\x12\r\n\x05score\x18\x01 \x03(\x02\"\x1c\n\ninitOutput\x12\x0e\n\x06status\x18\x01 \x01(\t\"0\n\x0finferenceOutput\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\r\n\x05score\x18\x02 \x01(\x02\x32\x9a\x01\n\x13objDetectModservice\x12\x39\n\x04init\x12\x16.objdetectgrpc.initArg\x1a\x19.objdetectgrpc.initOutput\x12H\n\tinference\x12\x1b.objdetectgrpc.inferenceArg\x1a\x1e.objdetectgrpc.inferenceOutputB\x10Z\x0e/objdetectgrpcb\x06proto3'
)




_INITARG = _descriptor.Descriptor(
  name='initArg',
  full_name='objdetectgrpc.initArg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='label_path', full_name='objdetectgrpc.initArg.label_path', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='num_classes', full_name='objdetectgrpc.initArg.num_classes', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='queue_size', full_name='objdetectgrpc.initArg.queue_size', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=37,
  serialized_end=107,
)


_INFERENCEARG = _descriptor.Descriptor(
  name='inferenceArg',
  full_name='objdetectgrpc.inferenceArg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='model_path', full_name='objdetectgrpc.inferenceArg.model_path', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='video_path', full_name='objdetectgrpc.inferenceArg.video_path', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='overlap_output_dir', full_name='objdetectgrpc.inferenceArg.overlap_output_dir', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='overlap_output', full_name='objdetectgrpc.inferenceArg.overlap_output', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='detected_output', full_name='objdetectgrpc.inferenceArg.detected_output', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='detected_output_dir', full_name='objdetectgrpc.inferenceArg.detected_output_dir', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='output_labeled_video_path', full_name='objdetectgrpc.inferenceArg.output_labeled_video_path', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=110,
  serialized_end=305,
)


_SCORES = _descriptor.Descriptor(
  name='scores',
  full_name='objdetectgrpc.scores',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='score', full_name='objdetectgrpc.scores.score', index=0,
      number=1, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=307,
  serialized_end=330,
)


_INITOUTPUT = _descriptor.Descriptor(
  name='initOutput',
  full_name='objdetectgrpc.initOutput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='objdetectgrpc.initOutput.status', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=332,
  serialized_end=360,
)


_INFERENCEOUTPUT = _descriptor.Descriptor(
  name='inferenceOutput',
  full_name='objdetectgrpc.inferenceOutput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='objdetectgrpc.inferenceOutput.status', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='score', full_name='objdetectgrpc.inferenceOutput.score', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=362,
  serialized_end=410,
)

DESCRIPTOR.message_types_by_name['initArg'] = _INITARG
DESCRIPTOR.message_types_by_name['inferenceArg'] = _INFERENCEARG
DESCRIPTOR.message_types_by_name['scores'] = _SCORES
DESCRIPTOR.message_types_by_name['initOutput'] = _INITOUTPUT
DESCRIPTOR.message_types_by_name['inferenceOutput'] = _INFERENCEOUTPUT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

initArg = _reflection.GeneratedProtocolMessageType('initArg', (_message.Message,), {
  'DESCRIPTOR' : _INITARG,
  '__module__' : 'objDetectMod_pb2'
  # @@protoc_insertion_point(class_scope:objdetectgrpc.initArg)
  })
_sym_db.RegisterMessage(initArg)

inferenceArg = _reflection.GeneratedProtocolMessageType('inferenceArg', (_message.Message,), {
  'DESCRIPTOR' : _INFERENCEARG,
  '__module__' : 'objDetectMod_pb2'
  # @@protoc_insertion_point(class_scope:objdetectgrpc.inferenceArg)
  })
_sym_db.RegisterMessage(inferenceArg)

scores = _reflection.GeneratedProtocolMessageType('scores', (_message.Message,), {
  'DESCRIPTOR' : _SCORES,
  '__module__' : 'objDetectMod_pb2'
  # @@protoc_insertion_point(class_scope:objdetectgrpc.scores)
  })
_sym_db.RegisterMessage(scores)

initOutput = _reflection.GeneratedProtocolMessageType('initOutput', (_message.Message,), {
  'DESCRIPTOR' : _INITOUTPUT,
  '__module__' : 'objDetectMod_pb2'
  # @@protoc_insertion_point(class_scope:objdetectgrpc.initOutput)
  })
_sym_db.RegisterMessage(initOutput)

inferenceOutput = _reflection.GeneratedProtocolMessageType('inferenceOutput', (_message.Message,), {
  'DESCRIPTOR' : _INFERENCEOUTPUT,
  '__module__' : 'objDetectMod_pb2'
  # @@protoc_insertion_point(class_scope:objdetectgrpc.inferenceOutput)
  })
_sym_db.RegisterMessage(inferenceOutput)


DESCRIPTOR._options = None

_OBJDETECTMODSERVICE = _descriptor.ServiceDescriptor(
  name='objDetectModservice',
  full_name='objdetectgrpc.objDetectModservice',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=413,
  serialized_end=567,
  methods=[
  _descriptor.MethodDescriptor(
    name='init',
    full_name='objdetectgrpc.objDetectModservice.init',
    index=0,
    containing_service=None,
    input_type=_INITARG,
    output_type=_INITOUTPUT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='inference',
    full_name='objdetectgrpc.objDetectModservice.inference',
    index=1,
    containing_service=None,
    input_type=_INFERENCEARG,
    output_type=_INFERENCEOUTPUT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_OBJDETECTMODSERVICE)

DESCRIPTOR.services_by_name['objDetectModservice'] = _OBJDETECTMODSERVICE

# @@protoc_insertion_point(module_scope)
