// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package visualnavigationgrpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// VisualNavigationModserviceClient is the client API for VisualNavigationModservice service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VisualNavigationModserviceClient interface {
	Init(ctx context.Context, in *InitArg, opts ...grpc.CallOption) (*InitOutput, error)
	Inference(ctx context.Context, in *InferenceArg, opts ...grpc.CallOption) (*InferenceOutput, error)
}

type visualNavigationModserviceClient struct {
	cc grpc.ClientConnInterface
}

func NewVisualNavigationModserviceClient(cc grpc.ClientConnInterface) VisualNavigationModserviceClient {
	return &visualNavigationModserviceClient{cc}
}

func (c *visualNavigationModserviceClient) Init(ctx context.Context, in *InitArg, opts ...grpc.CallOption) (*InitOutput, error) {
	out := new(InitOutput)
	err := c.cc.Invoke(ctx, "/visualnavigationgrpc.visualNavigationModservice/init", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *visualNavigationModserviceClient) Inference(ctx context.Context, in *InferenceArg, opts ...grpc.CallOption) (*InferenceOutput, error) {
	out := new(InferenceOutput)
	err := c.cc.Invoke(ctx, "/visualnavigationgrpc.visualNavigationModservice/inference", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VisualNavigationModserviceServer is the server API for VisualNavigationModservice service.
// All implementations must embed UnimplementedVisualNavigationModserviceServer
// for forward compatibility
type VisualNavigationModserviceServer interface {
	Init(context.Context, *InitArg) (*InitOutput, error)
	Inference(context.Context, *InferenceArg) (*InferenceOutput, error)
	mustEmbedUnimplementedVisualNavigationModserviceServer()
}

// UnimplementedVisualNavigationModserviceServer must be embedded to have forward compatible implementations.
type UnimplementedVisualNavigationModserviceServer struct {
}

func (UnimplementedVisualNavigationModserviceServer) Init(context.Context, *InitArg) (*InitOutput, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Init not implemented")
}
func (UnimplementedVisualNavigationModserviceServer) Inference(context.Context, *InferenceArg) (*InferenceOutput, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Inference not implemented")
}
func (UnimplementedVisualNavigationModserviceServer) mustEmbedUnimplementedVisualNavigationModserviceServer() {
}

// UnsafeVisualNavigationModserviceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VisualNavigationModserviceServer will
// result in compilation errors.
type UnsafeVisualNavigationModserviceServer interface {
	mustEmbedUnimplementedVisualNavigationModserviceServer()
}

func RegisterVisualNavigationModserviceServer(s grpc.ServiceRegistrar, srv VisualNavigationModserviceServer) {
	s.RegisterService(&VisualNavigationModservice_ServiceDesc, srv)
}

func _VisualNavigationModservice_Init_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitArg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VisualNavigationModserviceServer).Init(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/visualnavigationgrpc.visualNavigationModservice/init",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VisualNavigationModserviceServer).Init(ctx, req.(*InitArg))
	}
	return interceptor(ctx, in, info, handler)
}

func _VisualNavigationModservice_Inference_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InferenceArg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VisualNavigationModserviceServer).Inference(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/visualnavigationgrpc.visualNavigationModservice/inference",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VisualNavigationModserviceServer).Inference(ctx, req.(*InferenceArg))
	}
	return interceptor(ctx, in, info, handler)
}

// VisualNavigationModservice_ServiceDesc is the grpc.ServiceDesc for VisualNavigationModservice service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VisualNavigationModservice_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "visualnavigationgrpc.visualNavigationModservice",
	HandlerType: (*VisualNavigationModserviceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "init",
			Handler:    _VisualNavigationModservice_Init_Handler,
		},
		{
			MethodName: "inference",
			Handler:    _VisualNavigationModservice_Inference_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "visualNavigationMod.proto",
}
