# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: visualNavigationMod.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='visualNavigationMod.proto',
  package='visualnavigationgrpc',
  syntax='proto3',
  serialized_options=b'Z\025/visualnavigationgrpc',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x19visualNavigationMod.proto\x12\x14visualnavigationgrpc\"-\n\x0cinferenceArg\x12\r\n\x05input\x18\x01 \x01(\t\x12\x0e\n\x06output\x18\x02 \x01(\t\"S\n\x07initArg\x12\r\n\x05input\x18\x01 \x01(\t\x12\x0b\n\x03sec\x18\x02 \x01(\x02\x12\x16\n\x0eobjDetectModel\x18\x03 \x01(\t\x12\x14\n\x0csiameseModel\x18\x04 \x01(\t\"\x17\n\x06scores\x12\r\n\x05score\x18\x01 \x03(\x02\"\x1c\n\ninitOutput\x12\x0e\n\x06status\x18\x01 \x01(\t\"0\n\x0finferenceOutput\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\r\n\x05score\x18\x02 \x01(\x02\x32\xbd\x01\n\x1avisualNavigationModservice\x12G\n\x04init\x12\x1d.visualnavigationgrpc.initArg\x1a .visualnavigationgrpc.initOutput\x12V\n\tinference\x12\".visualnavigationgrpc.inferenceArg\x1a%.visualnavigationgrpc.inferenceOutputB\x17Z\x15/visualnavigationgrpcb\x06proto3'
)




_INFERENCEARG = _descriptor.Descriptor(
  name='inferenceArg',
  full_name='visualnavigationgrpc.inferenceArg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='input', full_name='visualnavigationgrpc.inferenceArg.input', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='output', full_name='visualnavigationgrpc.inferenceArg.output', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=51,
  serialized_end=96,
)


_INITARG = _descriptor.Descriptor(
  name='initArg',
  full_name='visualnavigationgrpc.initArg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='input', full_name='visualnavigationgrpc.initArg.input', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sec', full_name='visualnavigationgrpc.initArg.sec', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='objDetectModel', full_name='visualnavigationgrpc.initArg.objDetectModel', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='siameseModel', full_name='visualnavigationgrpc.initArg.siameseModel', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=98,
  serialized_end=181,
)


_SCORES = _descriptor.Descriptor(
  name='scores',
  full_name='visualnavigationgrpc.scores',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='score', full_name='visualnavigationgrpc.scores.score', index=0,
      number=1, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=183,
  serialized_end=206,
)


_INITOUTPUT = _descriptor.Descriptor(
  name='initOutput',
  full_name='visualnavigationgrpc.initOutput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='visualnavigationgrpc.initOutput.status', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=208,
  serialized_end=236,
)


_INFERENCEOUTPUT = _descriptor.Descriptor(
  name='inferenceOutput',
  full_name='visualnavigationgrpc.inferenceOutput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='visualnavigationgrpc.inferenceOutput.status', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='score', full_name='visualnavigationgrpc.inferenceOutput.score', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=238,
  serialized_end=286,
)

DESCRIPTOR.message_types_by_name['inferenceArg'] = _INFERENCEARG
DESCRIPTOR.message_types_by_name['initArg'] = _INITARG
DESCRIPTOR.message_types_by_name['scores'] = _SCORES
DESCRIPTOR.message_types_by_name['initOutput'] = _INITOUTPUT
DESCRIPTOR.message_types_by_name['inferenceOutput'] = _INFERENCEOUTPUT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

inferenceArg = _reflection.GeneratedProtocolMessageType('inferenceArg', (_message.Message,), {
  'DESCRIPTOR' : _INFERENCEARG,
  '__module__' : 'visualNavigationMod_pb2'
  # @@protoc_insertion_point(class_scope:visualnavigationgrpc.inferenceArg)
  })
_sym_db.RegisterMessage(inferenceArg)

initArg = _reflection.GeneratedProtocolMessageType('initArg', (_message.Message,), {
  'DESCRIPTOR' : _INITARG,
  '__module__' : 'visualNavigationMod_pb2'
  # @@protoc_insertion_point(class_scope:visualnavigationgrpc.initArg)
  })
_sym_db.RegisterMessage(initArg)

scores = _reflection.GeneratedProtocolMessageType('scores', (_message.Message,), {
  'DESCRIPTOR' : _SCORES,
  '__module__' : 'visualNavigationMod_pb2'
  # @@protoc_insertion_point(class_scope:visualnavigationgrpc.scores)
  })
_sym_db.RegisterMessage(scores)

initOutput = _reflection.GeneratedProtocolMessageType('initOutput', (_message.Message,), {
  'DESCRIPTOR' : _INITOUTPUT,
  '__module__' : 'visualNavigationMod_pb2'
  # @@protoc_insertion_point(class_scope:visualnavigationgrpc.initOutput)
  })
_sym_db.RegisterMessage(initOutput)

inferenceOutput = _reflection.GeneratedProtocolMessageType('inferenceOutput', (_message.Message,), {
  'DESCRIPTOR' : _INFERENCEOUTPUT,
  '__module__' : 'visualNavigationMod_pb2'
  # @@protoc_insertion_point(class_scope:visualnavigationgrpc.inferenceOutput)
  })
_sym_db.RegisterMessage(inferenceOutput)


DESCRIPTOR._options = None

_VISUALNAVIGATIONMODSERVICE = _descriptor.ServiceDescriptor(
  name='visualNavigationModservice',
  full_name='visualnavigationgrpc.visualNavigationModservice',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=289,
  serialized_end=478,
  methods=[
  _descriptor.MethodDescriptor(
    name='init',
    full_name='visualnavigationgrpc.visualNavigationModservice.init',
    index=0,
    containing_service=None,
    input_type=_INITARG,
    output_type=_INITOUTPUT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='inference',
    full_name='visualnavigationgrpc.visualNavigationModservice.inference',
    index=1,
    containing_service=None,
    input_type=_INFERENCEARG,
    output_type=_INFERENCEOUTPUT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_VISUALNAVIGATIONMODSERVICE)

DESCRIPTOR.services_by_name['visualNavigationModservice'] = _VISUALNAVIGATIONMODSERVICE

# @@protoc_insertion_point(module_scope)
