# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from service import visualNavigationMod_pb2 as visualNavigationMod__pb2


class visualNavigationModserviceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.init = channel.unary_unary(
                '/visualnavigationgrpc.visualNavigationModservice/init',
                request_serializer=visualNavigationMod__pb2.initArg.SerializeToString,
                response_deserializer=visualNavigationMod__pb2.initOutput.FromString,
                )
        self.inference = channel.unary_unary(
                '/visualnavigationgrpc.visualNavigationModservice/inference',
                request_serializer=visualNavigationMod__pb2.inferenceArg.SerializeToString,
                response_deserializer=visualNavigationMod__pb2.inferenceOutput.FromString,
                )


class visualNavigationModserviceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def init(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def inference(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_visualNavigationModserviceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'init': grpc.unary_unary_rpc_method_handler(
                    servicer.init,
                    request_deserializer=visualNavigationMod__pb2.initArg.FromString,
                    response_serializer=visualNavigationMod__pb2.initOutput.SerializeToString,
            ),
            'inference': grpc.unary_unary_rpc_method_handler(
                    servicer.inference,
                    request_deserializer=visualNavigationMod__pb2.inferenceArg.FromString,
                    response_serializer=visualNavigationMod__pb2.inferenceOutput.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'visualnavigationgrpc.visualNavigationModservice', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class visualNavigationModservice(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def init(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/visualnavigationgrpc.visualNavigationModservice/init',
            visualNavigationMod__pb2.initArg.SerializeToString,
            visualNavigationMod__pb2.initOutput.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def inference(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/visualnavigationgrpc.visualNavigationModservice/inference',
            visualNavigationMod__pb2.inferenceArg.SerializeToString,
            visualNavigationMod__pb2.inferenceOutput.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
